import { StyleSheet } from "react-native";
import { BASE_COLORS } from "@/constants/colors";
import { COMPONENT_FONT_SIZES, POPPINS_FONT } from "@/constants/fontSizes";

export default StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 0,
    marginTop: 0,
  },
  modalContainer: {
    width: "90%",
    maxWidth: 400,
    maxHeight: "90%",
    backgroundColor: "white",
    borderRadius: 20,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
  },
  headerTitle: {
    color: BASE_COLORS.white,
    fontFamily: POPPINS_FONT.medium,
    fontSize: COMPONENT_FONT_SIZES.card.title,
    textAlign: "center",
  },
  formContainer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  profilePictureContainer: {
    alignItems: "center",
    marginBottom: 10,
  },
  avatarContainer: {
    width: 90,
    height: 90,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    overflow: "visible",
  },
  avatarImage: {
    width: 90,
    height: 90,
    borderRadius: 50,
  },
  editPictureButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 27,
    height: 27,
    borderRadius: 20,
    backgroundColor: BASE_COLORS.blue,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "white",
  },
  passwordErrorText: {
    color: BASE_COLORS.orange,
    fontFamily: POPPINS_FONT.regular,
    fontSize: COMPONENT_FONT_SIZES.card.description,
    marginBottom: 12,
    textAlign: "center",
  },
  errorText: {
    color: BASE_COLORS.orange,
    fontFamily: POPPINS_FONT.regular,
    fontSize: COMPONENT_FONT_SIZES.card.description,
    textAlign: "center",
  },
  inputLabel: {
    fontSize: COMPONENT_FONT_SIZES.input.label,
    fontFamily: POPPINS_FONT.medium,
    color: BASE_COLORS.darkText,
    marginBottom: 5,
  },
  sectionTitle: {
    fontSize: COMPONENT_FONT_SIZES.card.subtitle,
    fontFamily: POPPINS_FONT.semiBold,
    color: BASE_COLORS.darkText,
    marginTop: 8,
    marginBottom: 12,
  },
  passwordToggleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 8,
  },
  passwordSection: {
    marginTop: 8,
  },
  saveButton: {
    paddingVertical: 6,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  saveButtonText: {
    color: "white",
    fontSize: COMPONENT_FONT_SIZES.button.medium,
    fontFamily: POPPINS_FONT.medium,
  },
  cancelButton: {
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  cancelButtonText: {
    fontSize: COMPONENT_FONT_SIZES.button.small,
    fontFamily: POPPINS_FONT.medium,
  },
  passwordField: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  validationIconContainer: {
    marginLeft: 10,
    height: 20,
    justifyContent: "center",
  },
  invalidPasswordWarning: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 4,
    marginTop: -8,
    marginBottom: 10,
  },
  invalidPasswordText: {
    color: BASE_COLORS.orange,
    fontFamily: POPPINS_FONT.regular,
    fontSize: COMPONENT_FONT_SIZES.card.description,
    marginLeft: 6,
  },
  googleUserInfoContainer: {
    flexDirection: "row",
    backgroundColor: BASE_COLORS.offWhite,
    borderRadius: 20,
    padding: 12,
    marginVertical: 14,
    alignItems: "flex-start",
    borderLeftWidth: 4,
  },
  googleUserInfoText: {
    marginLeft: 10,
    flex: 1,
    fontSize: COMPONENT_FONT_SIZES.card.subtitle,
    fontFamily: POPPINS_FONT.regular,
    lineHeight: 20,
  },
});
