import { StyleSheet } from "react-native";
import { BASE_COLORS } from "@/constant/colors";

export default StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 0,
    marginTop: 0,
  },
  modalContainer: {
    width: "90%",
    maxWidth: 400,
    maxHeight: "90%",
    backgroundColor: "white",
    borderRadius: 20,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  headerContainer: {
    padding: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: "Poppins-Medium",
    color: "white",
  },
  formContainer: {
    padding: 16,
  },
  profilePictureContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  avatarContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    overflow: "visible",
  },
  avatarImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  editPictureButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 32,
    height: 32,
    borderRadius: 20,
    backgroundColor: BASE_COLORS.blue,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "white",
  },
  passwordErrorText: {
    color: BASE_COLORS.orange,
    fontFamily: "Poppins-Regular",
    fontSize: 14,
    marginBottom: 12,
    textAlign: "center",
  },
  errorText: {
    color: BASE_COLORS.orange,
    fontFamily: "Poppins-Regular",
    fontSize: 14,
    marginBottom: 8,
    textAlign: "center",
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: "Poppins-Medium",
    color: BASE_COLORS.darkText,
    marginBottom: 4,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: "Poppins-SemiBold",
    color: BASE_COLORS.darkText,
    marginTop: 8,
    marginBottom: 12,
  },
  passwordToggleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 8,
  },
  passwordSection: {
    marginTop: 8,
  },
  saveButton: {
    paddingVertical: 8,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  saveButtonText: {
    color: "white",
    fontSize: 14,
    fontFamily: "Poppins-Medium",
  },
  cancelButton: {
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  cancelButtonText: {
    fontSize: 13,
    fontFamily: "Poppins-Medium",
  },
  passwordField: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  validationIconContainer: {
    marginLeft: 10,
    height: 20,
    justifyContent: "center",
  },
  invalidPasswordWarning: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 4,
    marginTop: -8,
    marginBottom: 16,
  },
  invalidPasswordText: {
    color: "#f59e0b",
    fontFamily: "Poppins-Regular",
    fontSize: 12,
    marginLeft: 6,
  },
  googleUserInfoContainer: {
    flexDirection: "row",
    backgroundColor: "#f2f0f0",
    borderRadius: 20,
    padding: 12,
    marginVertical: 16,
    alignItems: "flex-start",
    borderLeftWidth: 4,
  },
  googleUserInfoText: {
    marginLeft: 10,
    flex: 1,
    fontSize: 13,
    fontFamily: "Poppins-Regular",
    lineHeight: 20,
  },
});
