import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContainer: {
    width: "92%",
    maxWidth: 360,
    borderRadius: 28,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 15,
  },
  gradientBackground: {
    paddingVertical: 24,
    paddingHorizontal: 20,
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  headerSection: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  calendarIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 22,
    fontFamily: "Poppins-SemiBold",
    color: "#FFF",
  },
  wordCard: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 22,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    alignItems: "center",
  },
  languageBadge: {
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    paddingHorizontal: 18,
    paddingVertical: 7,
    borderRadius: 16,
    marginBottom: 16,
    transform: [{ translateY: -30 }],
  },
  languageText: {
    fontSize: 14,
    fontFamily: "Poppins-SemiBold",
    color: "#FFF",
  },
  wordText: {
    fontSize: 32,
    fontFamily: "Poppins-Bold",
    color: "#FFF",
    marginBottom: 10,
    textAlign: "center",
    letterSpacing: 0.5,
    marginTop: -20,
  },
  translationContainer: {
    width: "100%",
    alignItems: "center",
    marginBottom: 16,
  },
  dividerLine: {
    width: "50%",
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    marginBottom: 16,
  },
  translationText: {
    fontSize: 22,
    fontFamily: "Poppins-SemiBold",
    color: "rgba(255, 255, 255, 0.9)",
    textAlign: "center",
  },
  pronunciationContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 16,
    marginTop: 10,
  },
  pronunciationText: {
    fontSize: 17,
    fontFamily: "Poppins-SemiBold",
    color: "rgba(255, 255, 255, 0.9)",
    textAlign: "center",
    letterSpacing: 0.5,
  },
  audioContainer: {
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  playButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  playButtonActive: {
    backgroundColor: "rgba(255, 255, 255, 0.3)",
  },
  lottieContainer: {
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  lottieAnimation: {
    width: 60,
    height: 60,
  },
  audioTextContainer: {
    width: "100%",
    alignItems: "center",
  },
  audioLabelText: {
    fontSize: 13,
    fontFamily: "Poppins-Medium",
    color: "#FFF",
    marginBottom: 4,
    textAlign: "center",
  },
  noteContainer: {
    alignItems: "center",
    paddingHorizontal: 10,
    marginTop: 8,
  },
  noteText: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: "rgba(255, 255, 255, 0.7)",
    textAlign: "center",
  },
});

export default styles;
