import { BASE_COLORS } from "@/constant/colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContainer: {
    width: "92%",
    maxWidth: 360,
    borderRadius: 28,
    overflow: "hidden",
    paddingVertical: 24,
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 15,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    position: "relative",
  },
  decorativeCircle1: {
    position: "absolute",
    top: -80,
    right: -80,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: `${BASE_COLORS.blue}30`,
    zIndex: -1,
  },
  decorativeCircle2: {
    position: "absolute",
    bottom: -60,
    left: -60,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: `${BASE_COLORS.orange}30`,
    zIndex: -1,
  },
  closeButton: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  headerSection: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  calendarIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: BASE_COLORS.blue,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    shadowColor: BASE_COLORS.blue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  headerTitle: {
    fontSize: 22,
    fontFamily: "Poppins-SemiBold",
    color: BASE_COLORS.white,
  },
  wordCard: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 22,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    alignItems: "center",
  },
  languageBadge: {
    backgroundColor: BASE_COLORS.orange,
    paddingHorizontal: 18,
    paddingVertical: 7,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: BASE_COLORS.orange,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 3,
    transform: [{ translateY: -30 }],
  },
  languageText: {
    fontSize: 14,
    fontFamily: "Poppins-SemiBold",
    color: BASE_COLORS.white,
  },
  wordText: {
    fontSize: 32,
    fontFamily: "Poppins-Bold",
    color: BASE_COLORS.white,
    marginBottom: 10,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  translationContainer: {
    width: "100%",
    alignItems: "center",
    marginBottom: 16,
  },
  dividerLine: {
    width: "50%",
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    marginBottom: 16,
  },
  translationText: {
    fontSize: 22,
    fontFamily: "Poppins-SemiBold",
    color: BASE_COLORS.lightBlue,
    textAlign: "center",
  },
  pronunciationContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 16,
    marginTop: 10,
  },
  pronunciationText: {
    fontSize: 17,
    fontFamily: "Poppins-SemiBold",
    color: BASE_COLORS.orange,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  // Update these styles in the StyleSheet
  audioContainer: {
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  playButton: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: BASE_COLORS.blue,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    shadowColor: BASE_COLORS.blue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  playButtonActive: {
    backgroundColor: BASE_COLORS.orange,
    shadowColor: BASE_COLORS.orange,
  },
  lottieContainer: {
    width: 80,
    height: 80,
    justifyContent: "center",
    alignItems: "center",
  },
  lottieAnimation: {
    width: 80,
    height: 80,
  },
  audioTextContainer: {
    width: "100%",
    alignItems: "center",
  },
  audioLabelText: {
    fontSize: 13,
    fontFamily: "Poppins-Medium",
    color: BASE_COLORS.white,
    marginBottom: 4,
    textAlign: "center",
  },
  noteContainer: {
    alignItems: "center",
    paddingHorizontal: 10,
  },
  noteText: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: BASE_COLORS.white,
    opacity: 0.6,
    textAlign: "center",
  },
});

export default styles;
